project:
  type: book
  output-dir: docs

book:
  title: "DSP_DNS_Book"
  author: "Michał Lesiowski"
  favicon: "images/favicon.png"
  date: "2024-09-23"
  sharing: [twitter, facebook]
  downloads: [pdf, docx, epub]
  search: true
  version: "1.0.0"

  
  chapters:
    - index.qmd
    - intro.qmd
    - document.qmd
    - tables.qmd
    - galery.qmd
    - lightbox.qmd
    - summary.qmd
    - references.qmd
  
  appendices:
    - glossary.qmd
    
  page-footer: 
    right: "This page is built with [Quarto](https://quarto.org/)"
    left: "Wersja projektu: {{< meta book.version >}}"

  sidebar:
    logo: "images/LogoSRS3.png"
    pinned: true
    tools: 
      - icon: globe
        href: https://github.io
        text: "NMFS Open Science"
    search: true
    collapse-level: 1
  
  
bibliography: references.bib

format:
  html:
    theme: simplex
    fontsize: 1em
    linestretch: 1.5
    mainfont: Helvetica Neue, Helvetica, Arial, sans
    monofont: Cascadia Mono, Menlo, Consolas, Courier New, Courier
    backgroundcolor: "white"
    fontcolor: "black"
    knitr:
      opts_chunk:
        dev: "ragg_png"
    code-fold: true
    toc: true
    tbl-cap-location: bottom
    css: assets/custom.css
  pdf:
    pdf-engine: xelatex
    documentclass: scrreprt
    classoption: ["oneside", "open=any"]
    geometry: 
      - a4paper
      - left=2cm
      - right=2cm
      - top=2.5cm
      - bottom=2.5cm
      - columnsep=0cm
    titlepage: "plain"
    keep-tex: true
    number-sections: true
    number-depth: 2
    papersize: a4
    linestretch: 1.25
    include-in-header:
      text: |
        \usepackage{fontspec}
        \setmainfont{TeX Gyre Termes}[Scale=1.2]
        \usepackage{unicode-math}
    mainfont: "Times New Roman"
    sansfont: "Arial"
    monofont: "Courier New"
    code-overflow: wrap
    css: assets/print.css
  docx: 
    toc: true
    output-file: "DNS_DSP.docx"
    tbl-cap-location: bottom

editor: visual

